-- MySQL Script generated by MySQL Workbench
-- Sun Apr  3 20:17:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_wikiflix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_wikiflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_wikiflix` DEFAULT CHARACTER SET utf8 ;
USE `db_wikiflix` ;

-- -----------------------------------------------------
-- Table `db_wikiflix`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_wikiflix`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(60) NOT NULL,
  `id_hash` VARCHAR(60) NOT NULL,
  `alteracao_dt` DATETIME NULL,
  `cadastro_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_wikiflix`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_wikiflix`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `id_filme` INT NOT NULL,
  `id_comentario_resposta` INT NULL,
  `alteracao_dt` DATETIME NULL,
  `cadastro_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_comentarios_usuarios_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `db_wikiflix`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
